name: Check if a Docker image can be built

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  docker_build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.22
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: index_digest
          MYSQL_USER: test
          MYSQL_PASSWORD: p4ss
        ports:
        - "53306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      env:
        # @see https://docs.docker.com/develop/develop-images/build_enhancements/
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"
      run: |
        docker build . \
          --cache-from macbre/index-digest:latest \
          --build-arg COMMIT_SHA=$(git rev-parse --short HEAD) \
          --tag ${{ github.repository }}
        docker images
        docker inspect --format='{{json .Config.Labels}}' ${{ github.repository }} | jq

        docker ps

    - name: Check the version
      run: |
        docker run ${{ github.repository }} --version
  
    - name: Run the container and connect to the test database
      run: |
        docker run --network=host ${{ github.repository }} mysql://test:p4ss@0.0.0.0:53306/index_digest | tee /tmp/results
        grep "Jolly, good! No issues to report" /tmp/results
